In [2]:
import pandas as pd

df = pd.read_csv("final_fixed.csv")
df.tail(
    
)

,Name,Link,Ingredients,Main Spirit,Flavor,Rating,Ratings Count,Color,Occasion
376,Ooh La La Lemon,https://www.thecocktailproject.com/drink-recip...,"Pinnacle Whipped Vodka, Lemonade, Pinnacle Whi...",Vodka,Sweet,3,107,['yellow'],"['birthday', 'ladies-night', 'spring', 'summer']"
377,Classic Cosmo,https://www.thecocktailproject.com/drink-recip...,"EFFEN Vodka, Cranberry Juice, EFFEN Vodka, Cra...",Vodka,Sweet,3,60,['red'],"['ladies-night', 'summer']"
378,Strawberry Basil,https://www.thecocktailproject.com/drink-recip...,"Strawberries, Strawberries, Basil, Soda Water,...",Vodka,Fruity,3,39,['pink'],"['bbq', 'summer']"
379,Skinnygirl Bloody Mary,https://www.thecocktailproject.com/drink-recip...,"Skinnygirl Cucumber Vodka, Hot Sauce, Skinnygi...",Vodka,Savory,3,46,['red'],['brunch']
380,Handsome Ginger,https://www.thecocktailproject.com/drink-recip...,"Pinnacle Original Vodka, Ginger Beer, Pinnacle...",Vodka,Sweet,3,45,['clear'],['summer']

In [4]:
df['Occasion']

0           ['birthday', 'fall', 'new-years', 'winter']
1       ['birthday', 'holiday', 'new-years', 'wedding']
2                                  ['spring', 'summer']
3                 ['bbq', 'brunch', 'spring', 'summer']
4                 ['bbq', 'brunch', 'spring', 'summer']
                             ...
376    ['birthday', 'ladies-night', 'spring', 'summer']
377                          ['ladies-night', 'summer']
378                                   ['bbq', 'summer']
379                                          ['brunch']
380                                          ['summer']
Name: Occasion, Length: 381, dtype: object